"""LLM output filter scanner for detecting PII in free-text generated by LLMs."""

from __future__ import annotations

import time
from .scanner import ResultScanner, ScanVerdict, ScanFinding

try:
    from presidio_analyzer import AnalyzerEngine

    PRESIDIO_AVAILABLE = True
except ImportError:
    PRESIDIO_AVAILABLE = False


class LLMOutputFilterScanner(ResultScanner):
    """
    Specialized scanner for LLM-generated free-text output.

    Uses Presidio in analyze mode with lower confidence thresholds
    and additional entity types to catch PII that LLMs may embed
    in generated text.
    """

    def __init__(
        self,
        languages: list[str] | None = None,
        confidence_threshold: float = 0.5,  # Lower threshold for LLM output
    ):
        self._languages = languages or ["en"]
        self._confidence_threshold = confidence_threshold
        self._analyzer: AnalyzerEngine | None = None

    def _get_analyzer(self) -> AnalyzerEngine:
        if not PRESIDIO_AVAILABLE:
            raise RuntimeError("presidio-analyzer is not installed")
        if self._analyzer is None:
            self._analyzer = AnalyzerEngine()
        return self._analyzer

    @property
    def scanner_type(self) -> str:
        return "llm_output_filter"

    @property
    def scanner_version(self) -> str:
        return "1.0.0"

    def _extract_freetext_values(self, result: dict) -> list[tuple[str, str]]:
        """Extract only free-text fields that LLMs might have generated."""
        values = []
        for i, extraction in enumerate(result.get("extractions", [])):
            # Check tables for pii_bearing columns
            for j, table in enumerate(extraction.get("tables", [])):
                columns = table.get("columns", [])
                for k, row in enumerate(table.get("rows", [])):
                    for col_idx, cell in enumerate(row):
                        if isinstance(cell, str) and col_idx < len(columns):
                            col = columns[col_idx]
                            if col.get("pii_bearing", False):
                                values.append(
                                    (
                                        f"extractions[{i}].tables[{j}].rows[{k}][{col_idx}]({col.get('name', '')})",
                                        cell,
                                    )
                                )

            # All string fields are potentially LLM-generated free text
            for key, val in extraction.get("fields", {}).items():
                if isinstance(val, str) and len(val) > 20:  # Only scan non-trivial text
                    values.append((f"extractions[{i}].fields.{key}", val))

        return values

    def scan(self, result: dict, contract: dict | None = None) -> ScanVerdict:
        start = time.monotonic()
        findings: list[ScanFinding] = []

        freetext_values = self._extract_freetext_values(result)
        stats = {
            "freetext_fields_scanned": len(freetext_values),
            "presidio_available": PRESIDIO_AVAILABLE,
            "confidence_threshold": self._confidence_threshold,
        }

        if not PRESIDIO_AVAILABLE:
            elapsed_ms = int((time.monotonic() - start) * 1000)
            return ScanVerdict(
                scanner_type="llm_output_filter",
                scanner_version=self.scanner_version,
                passed=False,
                findings=[],
                statistics={**stats, "error": "presidio not available"},
                action_taken="error",
                scan_duration_ms=elapsed_ms,
            )

        analyzer = self._get_analyzer()

        # Broader entity types for LLM output
        entity_types = [
            "PERSON",
            "PHONE_NUMBER",
            "EMAIL_ADDRESS",
            "CREDIT_CARD",
            "IBAN_CODE",
            "US_SSN",
            "US_PASSPORT",
            "LOCATION",
            "ORGANIZATION",
            "DATE_TIME",
            "NRP",
            "MEDICAL_LICENSE",
            "URL",
        ]

        for path, value in freetext_values:
            for lang in self._languages:
                try:
                    results = analyzer.analyze(
                        text=value,
                        language=lang,
                        entities=entity_types,
                        score_threshold=self._confidence_threshold,
                    )
                except Exception:
                    continue

                for r in results:
                    snippet = value[:3] + "..." if len(value) > 3 else value
                    findings.append(
                        ScanFinding(
                            field_path=path,
                            entity_type=r.entity_type,
                            confidence=r.score,
                            value_snippet=snippet,
                            scanner_type="llm_output_filter",
                        )
                    )

        elapsed_ms = int((time.monotonic() - start) * 1000)
        stats["findings_count"] = len(findings)

        return ScanVerdict(
            scanner_type="llm_output_filter",
            scanner_version=self.scanner_version,
            passed=len(findings) == 0,
            findings=findings,
            statistics=stats,
            action_taken="blocked" if findings else "none",
            scan_duration_ms=elapsed_ms,
        )
